services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: music_recommendation
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
