M python:3.9

# Set the working directory
WORKDIR /app

# Copy the API code to the container
COPY . /app

# Install dependencies
RUN pip install -r requirements.txt

# Expose the Flask port
EXPOSE 5000

# Run the Flask application
CMD ["python", "app.py"]
